name: Node JS Package Upload
on:
  workflow_dispatch:
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
              always-auth: true
              node-version: '20.x'
              registry-url: https://registry.npmjs.org
              scope: '@octocat'
        - name: Install dependencies
          run: npm ci
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            
